import { Platform, StyleSheet } from "react-native";

export const colors = {
  navy: "#13213C",
  indigo: "#3B4CCA",
  sky: "#EAF2FF",
  white: "#FFFFFF",
  ink: "#172033",
  muted: "#63708A",
  border: "#DDE4F0",
  lavender: "#F5F6FF",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  content: {
    alignItems: "center",
    width: "100%",
  },
  title: {
    color: colors.ink,
    fontFamily: Platform.select({ ios: "Avenir Next", android: "sans-serif-condensed", default: "sans-serif" }),
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
  subtitle: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
    textAlign: "center",
  },
  card: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    padding: 20,
    shadowColor: "#1B2A4A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  input: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 16,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    width: "100%",
  },
  label: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 18,
    width: "100%",
  },
  button: {
    alignItems: "center",
    backgroundColor: colors.indigo,
    borderRadius: 14,
    flexDirection: "row",
    justifyContent: "center",
    minHeight: 54,
    paddingHorizontal: 18,
    width: "100%",
  },
  buttonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  backButton: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 22,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  backButtonText: {
    color: colors.indigo,
    fontSize: 15,
    fontWeight: "800",
  },
  iconCircle: {
    alignItems: "center",
    backgroundColor: "#DFE5FF",
    borderRadius: 34,
    height: 68,
    justifyContent: "center",
    width: 68,
  },
  inputRow: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 15,
    width: "100%",
  },
});
